server:
    port: 9091 

spring:
  application:
    name: GREET_API
    
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
management:
  endpoints:
    web:
      exposure:
        include: '*' 
           
